# Generated by Django 2.0.6 on 2018-06-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_auto_20180610_1121'),
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
    ]
